databases:
  - name: EventBrite
    databaseName: EventBrite
    user: EventBrite
    plan: free

services:
  - type: web
    plan: free
    name: EventBrite
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: EventBrite
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false