databases:
  - name: event_brite
    databaseName: event_brite
    user: event_brite
    plan: free

services:
  - type: web
    plan: free
    name: event_brite
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: event_brite
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false